sudo: false
language: node_js
branches:
  only:
  - master
  - "/^v\\d+\\.\\d+\\.\\d+$/"
node_js:
  - '6'
  - '8'
script: npm run test
deploy:
  provider: npm
  on:
    tags: true
    repo: CoursePark/eslint-config-bluedrop-legacy
    node: '8'
